version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/alerts.yml:/etc/prometheus/alerts.yml:ro
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./ops/dashboards:/var/lib/grafana/dashboards
      - ./ops/provisioning:/etc/grafana/provisioning


