version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: workflow-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: workflow-builder
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - workflow-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: workflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workflow-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workflow-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/workflow-builder?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key
      ENCRYPTION_KEY: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
      SLACK_CLIENT_ID: 9414711188336.9386077956261
      SLACK_CLIENT_SECRET: fe5210e8be25ad8527df10297a935f42
      SLACK_SIGNING_SECRET: a80829f35c80b79a56d308cec8033350
      PORT: 5000
      BASE_URL: http://localhost:5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    networks:
      - workflow-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workflow-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_SLACK_CLIENT_ID: 9414711188336.9386077956261
      NEXT_PUBLIC_ENVIRONMENT: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - workflow-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  workflow-network:
    driver: bridge
